name: Automation Robot
on: 
  push: {}
  schedule:
    - cron:  '*/6 * * * *'
    
jobs: 
  run-automation-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      - run: npm install
      - name: run
        uses: mujo-code/puppeteer-headful@v2
        env:
          CI: true
        with:
          args: npm test
